-- CREAR BASE DATOS
CREATE DATABASE IF NOT EXISTS DEMO;

-- USAR LA BASE DE DATOS
USE DATOS;

-- CREAR UNA TABLA
CREATE TABLE
     IF NOT EXISTS datos (
          id INT AUTO_INCREMENT PRIMARY KEY,
          nombres VARCHAR(255) NOT NULL,
          apellidos VARCHAR(255) NOT NULL,
          dni VARCHAR(15) NOT NULL,
          fechaNacimiento DATE NOT NULL,
          fechaRegistro TIMESTAMP DEFAULT CURRENT_TIMESTAMP
     );

-- ELIMINAR UNA BASE DE DATOS
DROP DATABASE DEMO;

-- ELIMINAR UNA TABLA
DROP TABLE DATOS;